---
- name: Configure server with nginx and TLS
  hosts: webservers
  become: True
  become_method: sudo

  vars:
    server_name: testserver1.oreilly.lab
    homepage: /usr/share/nginx/html/index.html
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file_available: /etc/nginx/sites-available/default
    conf_file_enabled: /etc/nginx/sites-enabled/default

  tasks:
    - name: Install nginx
      package: name=nginx update_cache=yes cache_valid_time=3600

    - name: Create directories for SSL certificate
      file: path=/etc/nginx/ssl state=directory

    - name: Copy TLS-key file
      copy: src=files/nginx.key dest={{ key_file }} owner=root mode=0600
      notify: restart nginx

    - name: Copy TLS-certificate file
      copy: src=files/nginx.crt dest={{ cert_file }}
      notify: restart nginx

    - name: Copy nginx config file
      template: src=templates/nginx.conf.j2 dest={{ conf_file_available }}
      notify: restart nginx

    - name: Enable nginx configuration
      file: >
        dest={{ conf_file_enabled }}
        src={{ conf_file_available }}
        state=link
      notify: restart nginx

    - name: Copy index.html file
      template: src=templates/index.html.j2 dest={{ homepage }} mode=0644

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

    - name: reload nginx
      service: name=nginx state=reloaded
