---
  - name: "vagrant"
    url:  "http://files.vagrantup.com/precise64.box"
    ip:    192.168.50.150


  - name: "postgresql"
    url:  "http://files.vagrantup.com/precise64.box"
    ip:    192.168.60.150

  - name: "riak"
    url:  "http://files.vagrantup.com/precise64.box"
    ip:    192.168.70.150
    nodes: 3
