VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use the same key for each machine
  config.ssh.insert_key = false

  config.vm.define "vagrant1" do |vagrant1|
    vagrant1.vm.box = "ubuntu/trusty64"
    vagrant1.vm.host_name = "vagrant1"

    vagrant1.vm.network :private_network, ip: "192.168.0.101"
    vagrant1.vm.network :forwarded_port, guest: 80, host: 8080
    vagrant1.vm.network :forwarded_port, guest: 443, host: 8443

    vagrant1.vm.provider "virtualbox" do |vb|
      vb.name = "vagrant1"
    end
  end

  config.vm.define "vagrant2" do |vagrant2|
    vagrant2.vm.box = "ubuntu/trusty64"
    vagrant2.vm.host_name = "vagrant2"

    vagrant2.vm.network :private_network, ip: "192.168.0.102"
    vagrant2.vm.network :forwarded_port, guest: 80, host: 8081
    vagrant2.vm.network :forwarded_port, guest: 443, host: 8444

    vagrant2.vm.provider "virtualbox" do |vb|
      vb.name = "vagrant2"
    end
  end

  config.vm.define "vagrant3" do |vagrant3|
    vagrant3.vm.box = "ubuntu/trusty64"
    vagrant3.vm.host_name = "vagrant3"

    vagrant3.vm.network :private_network, ip: "192.168.0.103"
    vagrant3.vm.network :forwarded_port, guest: 80, host: 8082
    vagrant3.vm.network :forwarded_port, guest: 443, host: 8445

    vagrant3.vm.provider "virtualbox" do |vb|
      vb.name = "vagrant3"
    end
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 512
    vb.cpus = 1
    vb.linked_clone = true
  end

end