Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "web01"
  config.vm.network "private_network", ip: "192.168.33.20"
  config.vm.provider "virtualbox" do |vbox|
    vbox.gui = "false"
    vbox.name = "web01"
    vbox.linked_clone = "true"
    vbox.cpus = 2
    vbox.memory = 1024
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/testplaybook.yml"
    ansible.extra_vars = {
        ansible_python_interpreter: "/usr/bin/python2",
    }
  end
end